apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
      - name: {{ .Values.application.name }}
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.application.containerPort }}
        volumeMounts:
          - name: {{ .Values.application.name }}-configmap-volume
            mountPath: usr/share/nginx/html
      volumes:
        - name: {{ .Values.application.name }}-configmap-volume
          configMap:
            name: {{ .Values.application.name }}-configmap
